### PR TITLE
Support AAC tracks with custom sizelength, indexlength and indexdeltalength

### PR DESCRIPTION
**Pull request by BenLocal**
repull for #114

When proxying a rtsp, there is only sizelength, no indexlength in its sdp, , in aac payload, AU-headers-length is 000d, not 0010, so it will be error invalid AU-headers-length (13) when decoding.

sdp info:
```
v=0
o=- 040d498c 1 IN IP4 172.20.64.45
s=server name:ams32 172.20.64.45
i=stream/0
t=0 0
a=tool:AMS32 v1.0
a=type:broadcast
a=type:control:*
a=range:npt=0-
m=video 0 RTP/AVP 96
c=IN IP4 0.0.0.0
a=rtpmap:96 H264/90000
a=control:track1
a=fmtp:96 sprop-parameter-sets=Z2QAKq2EAQwgCGEAQwgCGEAQwgCEO1A8ARPywgAAAwACAAADAHkI,aO48sA==
m=audio 0 RTP/AVP 97
c=IN IP4 0.0.0.0
a=rtpmap:97 mpeg4-generic/48000/2
a=control:track2
a=fmtp: 97 streamtype=3;profile-level-id=14;mode=AAC-hbr;config=1190;sizeLength=13
```

### CODE REVIEW

**Comment by aler9** [comment]
We're getting really close, thank you very much.

There's a missing part, `indexDeltaLength` is not taken into consideration by the decoder; you should add a field `IndexDeltaLength` and use it in this way:

```go
func (d *Decoder) parseAuData(payload []byte,
	headersLenBytes int,
	headerCount int,
) (dataLens []uint64, err error) {
	if len(payload) < headersLenBytes {
		return nil, fmt.Errorf("payload is too short")
	}

	br := bitio.NewReader(bytes.NewBuffer(payload[:headersLenBytes]))
	for i := 0; i < headerCount; i++ {
		dataLen, err := br.ReadBits(uint8(d.SizeLength))
		if err != nil {
			return nil, fmt.Errorf("payload is too short")
		}

		if i == 0 {
			if d.IndexLength > 0 {
				auIndex, err := br.ReadBits(uint8(d.IndexLength))
				if err != nil {
					return nil, fmt.Errorf("payload is too short")
				}

				if auIndex != 0 {
					return nil, fmt.Errorf("AU-index field is not zero")
				}
			}
		} else {
			if d.IndexDeltaLength > 0 {
				(read index delta and check if it's zero)
			}
		}

		dataLens = append(dataLens, dataLen)
	}
	return dataLens, nil
}
```

**Comment by BenLocal** [comment]
Fixed, I had mistakenly thought that `Index Length` and `Index DataLength` were always the same. 

If this is the case, ffmpeg's `rtpdec_mpeg4.c` code confuses me, he doesn't use `IndexDeltaLength`，is this wrong.

https://github.com/FFmpeg/FFmpeg/blob/ea84eb2db13f9a2df78de431b993780f9562f642/libavformat/rtpdec_mpeg4.c#L168
``` c
    for (i = 0; i < data->nb_au_headers; ++i) {
        data->au_headers[i].size  = get_bits_long(&getbitcontext, data->sizelength);
        data->au_headers[i].index = get_bits_long(&getbitcontext, data->indexlength);
    }
```

**Comment by aler9** [comment]
Yes, they're wrong, in RFC 3640 is clearly stated that:

```
      indexLength:
      The number of bits on which the AU-Index is encoded in the first
      AU-header.  The default value of zero indicates the absence of the
      AU-Index field in each first AU-header.

      indexDeltaLength:
      The number of bits on which the AU-Index-delta field is encoded in
      any non-first AU-header.  The default value of zero indicates the
      absence of the AU-Index-delta field in each non-first AU-header.
```

Anyway, these values are seldom touched, personally i've never seen them from being different then 3.

**Comment by aler9** [comment]
merged, thanks!

**Comment by aler9** [comment]
Anyway, in my opinion your camera uses `indexlength=3; indexdeltalength=3`, it just omits them, since the header length must always be a multiple of 8..

**Comment by BenLocal** [comment]
1. Actually, my camera use `sizelength=13;indexlength=0; indexdeltalength=0`, because of the AU-headers-length value is `000d` , 13 bits and 3 zero-padding
2. I think the AU-headers-length value may not be a multiple of 8, allowing up to 7 zero-padding
only those describing AU in rfc3640，not sure correct：
```
 If the concatenated AU-headers consume a
   non-integer number of octets, up to 7 zero-padding bits MUST be
   inserted at the end in order to achieve octet-alignment of the AU
   Header Section.
```

**Comment by aler9** [comment]
Thanks, i completely missed that out, now this is supported too.

**Pull request merged**
