### PR TITLE
client: allow RTP packets to come from a different source that RTSP host

### PR DESCRIPTION
**Pull request by lionelnicolas**
This is related to a discussion which happened in that PR few month ago : https://github.com/aler9/gortsplib/pull/21#issuecomment-763992570

### CODE REVIEW

**Comment by aler9** [comment]
This feature is provided through `AnyPortEnable` since ba7f9aff

**Comment by lionelnicolas** [comment]
The commit you mentioned doesn't cover all features of that PR.

Here is a schematic showing why I need the host IP check to be skipped as well (sorry I should have started by that when creating the PR).

If a client written with gortsplib wants to pull a stream through a load balancer (`192.168.0.1`), and is being proxied to `192.168.0.11`, then UDP traffic is going to come from `192.168.0.11`. In the current implementation, the client is going to discard media packets because they are not coming from the load balancer IP address. This PR allows the developer to remove that check.

schema

An alternative could be if the load balancer performs an RTSP `302 Redirect` to RTSP server A, but then you loose the ability to track RTSP connections in the load balancer.

**Comment by aler9** [comment]
Hello, in order to load balance i usually prefer the second configuration you described (the 302 redirect-way), since the load balancer can be shut down or restarted independently from the stream, and it's the standard way to perform the task (for instance, it is used in Apache Leshan).

Anyway it's possible to enhance the client to support your configuration, but in my opinion this can be done not by disabling the IP check, but by editing the SETUP response and adding a source parameter, that contains the source IP of the UDP packets (like the RFC tells to do):

```
RTSP/1.0 200 OK
CSeq: 302
Date: 23 Jan 1997 15:35:06 GMT
Session: 47112344
Transport: RTP/AVP;unicast;
client_port=4588-4589;server_port=6256-6257,source=192.168.0.13
```

**Comment by tmatth** [comment]
> Hello, in order to load balance i usually prefer the second configuration you described (the 302 redirect-way), since the load balancer can be shut down or restarted independently from the stream, and it's the standard way to perform the task (for instance, it is used in Eclipse Leshan).
> 
> Anyway it's possible to enhance the client to support your configuration, but in my opinion this can be done not by disabling the IP check, but by editing the SETUP response sent by the server and adding a source parameter, that contains the source IP of the UDP packets (like the RFC tells to do):
> 
> ```
> RTSP/1.0 200 OK
> CSeq: 302
> Date: 23 Jan 1997 15:35:06 GMT
> Session: 47112344
> Transport: RTP/AVP;unicast;
> client_port=4588-4589;server_port=6256-6257,source=192.168.0.13
> ```

I think it's intended to be `src_addr` no?

>  src_addr:  A general source address parameter that can contain one or
         more address specifications.  Each combination of
         protocol/profile/lower transport needs to have the format and
         interpretation of its address specification defined.  For
         RTP/AVP/UDP and RTP/AVP/TCP, the address specification is a
         tuple containing a host address and port.

> **This parameter MUST be specified by the server if it transmits
         media packets from an address other than the one RTSP messages
         are sent to**.  This will allow the client to verify the source
         address and give it a destination address for its RTCP feedback
         packets, if RTP is used.  The address or addresses indicated in
         the src_addr parameter SHOULD be used both for the sending and
         receiving of the media stream's data packets.  The main reasons
         are threefold: First, indicating the port and source address(s)
         lets the receiver know where from the packets is expected to
         originate.  Second, traversal of NATs is greatly simplified
         when traffic is flowing symmetrically over a NAT binding.
         Third, certain NAT traversal mechanisms need to know to which
         address and port to send so-called "binding packets" from the
         receiver to the sender, thus creating an address binding in the
         NAT that the sender-to-receiver packet flow can use.

 > This information may also be available through SDP.
        However, since this is more a feature of transport than
        media initialization, the authoritative source for this
        information should be in the SETUP response.

Strictly speaking this is required by RTSP 2.0 but not included in RTSP 1.0

**Comment by tmatth** [comment]
> > Hello, in order to load balance i usually prefer the second configuration you described (the 302 redirect-way), since the load balancer can be shut down or restarted independently from the stream, and it's the standard way to perform the task (for instance, it is used in Eclipse Leshan).
> > Anyway it's possible to enhance the client to support your configuration, but in my opinion this can be done not by disabling the IP check, but by editing the SETUP response sent by the server and adding a source parameter, that contains the source IP of the UDP packets (like the RFC tells to do):
> > ```
> > RTSP/1.0 200 OK
> > CSeq: 302
> > Date: 23 Jan 1997 15:35:06 GMT
> > Session: 47112344
> > Transport: RTP/AVP;unicast;
> > client_port=4588-4589;server_port=6256-6257,source=192.168.0.13
> > ```
> 
> I think it's intended to be `src_addr` no?

Oh nevermind, it's `source` in https://www.rfc-editor.org/rfc/rfc2326:
>    source:
>       If the source address for the stream is different than can be
>     derived from the RTSP endpoint address (the server in playback
>   or the client in recording), the source MAY be specified.

**Pull request closed without merging**
