### PR TITLE
an error case

### PR DESCRIPTION
**Pull request by langhuihui**

### CODE REVIEW

**Comment by aler9** [comment]
The current behavior is wanted, as an implementation is expected to return both Response (sent to client) and err (shown into server).

**Comment by langhuihui** [comment]
if connect to a rtsp that is not exist,it will panic

**Comment by langhuihui** [comment]
res will be nil

**Comment by aler9** [comment]
If you want to notify an user about a non-existing stream, you have to return a Response with a StatusCode of NotFound and a nil error.
An error is not enough since it doesn't allow to set the status code that is returned to the user.
There are tons of examples in both gortsplib and rtsp-simple-servers.

**Pull request closed without merging**
