### PR TITLE
Fix parse for trackID if not last parameter 

### PR DESCRIPTION
**Pull request by frjol**
See issue #61

### CODE REVIEW

**Comment by aler9** [comment]
Hello, can you provide an example on how that URL is generated?
SETUP URLs are built by putting together data provided by the server through a DESCRIBE response, in particular the `Content-Base` header and the SDP.
That URL was generated by the server by passing query parameters to the DESCRIBE method or was built by scratch by a client?

**Comment by frjol** [comment]
Hello,
The url is built by the server but the server also accepts url parameters to change various settings.
You can see the url with the parameters in the issue #61.

> 
> 
> In my case I have
> `ERR: Unable to parse track ID (manufacturer-media/media.amp?videocodec=h264&audio=0&resolution=5472x3648&camera=1&compression=30&rotation=0&fps=0&h264profile=Main&videobitratemode=vbr&videokeyframeinterval=100&videozstrength=10&videozgopmode=fixed&videozfpsmode=fixed/trackID=0?videocodec=h264&audio=0&resolution=5472x3648&camera=1&compression=30&rotation=0&fps=0&h264profile=Main&videobitratemode=vbr&videokeyframeinterval=100&videozstrength=10&videozgopmode=fixed&videozfpsmode=fixed)`
> 
> It looks like it could simply be fixed by extracting the ID part of the string.

I hope this is clearer. 
Thanks!

**Comment by aler9** [comment]
Sorry but i can't replicate the issue, i tested with both ffmpeg and GStreamer. Let's suppose that they want to read a stream with this URL:

```
rtsp://localhost:8554/manufacturer-media/media.amp?videocodec=h264&audio=0&resolution=5472x3648&camera=1&compression=30&rotation=0&fps=0&h264profile=Main&videobitratemode=vbr&videokeyframeinterval=100&videozstrength=10&videozgopmode=fixed&videozfpsmode=fixed
```

They send to the server this DESCRIBE request:

```
DESCRIBE rtsp://localhost:8554/manufacturer-media/media.amp?videocodec=h264&audio=0&resolution=5472x3648&camera=1&compression=30&rotation=0&fps=0&h264profile=Main&videobitratemode=vbr&videokeyframeinterval=100&videozstrength=10&videozgopmode=fixed&videozfpsmode=fixed RTSP/1.0
CSeq: 2
User-Agent: GStreamer/1.16.2
Accept: application/sdp
Date: Mon, 26 Jul 2021 15:46:07 GMT
```

gortsplib's server replies with:

```
RTSP/1.0 200 OK
CSeq: 2
Content-Base: rtsp://localhost:8554/manufacturer-media/media.amp?videocodec=h264&audio=0&resolution=5472x3648&camera=1&compression=30&rotation=0&fps=0&h264profile=Main&videobitratemode=vbr&videokeyframeinterval=100&videozstrength=10&videozgopmode=fixed&videozfpsmode=fixed/
Content-Length: 466
Content-Type: application/sdp
Server: gortsplib

v=0
o=- 0 0 IN IP4 127.0.0.1
s=Stream
c=IN IP4 0.0.0.0
t=0 0
m=video 0 RTP/AVP 96
b=AS:5675
a=rtpmap:96 H264/90000
a=fmtp:96 packetization-mode=1; sprop-parameter-sets=Z2QAKKzZQHgCJ+WEAAADAAQAAAMA8Dxgxlg=,aOvjyyLA; profile-level-id=640028
a=control:trackID=0
m=audio 0 RTP/AVP 97
b=AS:128
a=rtpmap:97 MPEG4-GENERIC/48000/2
a=fmtp:97 profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3; config=119056E500
a=control:trackID=1
```

Then they both send the right URL, that is the one with /trackID=0 at the end, not before all parameters:

```
SETUP rtsp://localhost:8554/manufacturer-media/media.amp?videocodec=h264&audio=0&resolution=5472x3648&camera=1&compression=30&rotation=0&fps=0&h264profile=Main&videobitratemode=vbr&videokeyframeinterval=100&videozstrength=10&videozgopmode=fixed&videozfpsmode=fixed/trackID=0 RTSP/1.0
CSeq: 3
User-Agent: GStreamer/1.16.2
Transport: RTP/AVP;unicast;client_port=46478-46479
Date: Mon, 26 Jul 2021 15:46:07 GMT
```

Which client are you using?

**Comment by frjol** [comment]
In my case, it's a proprietary rtsp client. Sadly, I cannot disclose the origin of this client for now. 
It works with most cameras on the market. I will try to find another example.
In any case, my solution keeps the same behavior as before.

**Comment by aler9** [comment]
Your proprietary client is generating an invalid URL; RTSP URLs work in a slightly different way than standard URLs, and track ID must be always appended to the URL, prefixed by a slash, regardless of the presence of query parameters.

This is wrong:

```
rtsp://localhost:8554/manufacturer-media/media.amp?videocodec=h264&audio=0&resolution=5472x3648&camera=1&compression=30&rotation=0&fps=0&h264profile=Main&videobitratemode=vbr&videokeyframeinterval=100&videozstrength=10&videozgopmode=fixed&videozfpsmode=fixed/trackID=0?videocodec=h264&audio=0&resolution=5472x3648&camera=1&compression=30&rotation=0&fps=0&h264profile=Main&videobitratemode=vbr&videokeyframeinterval=100&videozstrength=10&videozgopmode=fixed&videozfpsmode=fixed
```

This is right:

```
rtsp://localhost:8554/manufacturer-media/media.amp?videocodec=h264&audio=0&resolution=5472x3648&camera=1&compression=30&rotation=0&fps=0&h264profile=Main&videobitratemode=vbr&videokeyframeinterval=100&videozstrength=10&videozgopmode=fixed&videozfpsmode=fixed/trackID=0
```

Edit your RTSP client to follow this behavior, otherwise it won't work with every RTSP server or camera.

**Comment by frjol** [comment]
Thanks for the explanation. Do you have any reference of that spcecification?

**Pull request closed without merging**
