### PR TITLE
aac decode with sdp sizelength and indexlength

### PR DESCRIPTION
**Pull request by BenLocal**
When proxying a rtsp, there is only sizelength, no indexlength in its sdp, , in aac payload, AU-headers-length is `000d`, not `0010`, so it will be error `invalid AU-headers-length (13)` when decoding.

sdp info:
```
v=0
o=- 040d498c 1 IN IP4 172.20.64.45
s=server name:ams32 172.20.64.45
i=stream/0
t=0 0
a=tool:AMS32 v1.0
a=type:broadcast
a=type:control:*
a=range:npt=0-
m=video 0 RTP/AVP 96
c=IN IP4 0.0.0.0
a=rtpmap:96 H264/90000
a=control:track1
a=fmtp:96 sprop-parameter-sets=Z2QAKq2EAQwgCGEAQwgCGEAQwgCEO1A8ARPywgAAAwACAAADAHkI,aO48sA==
m=audio 0 RTP/AVP 97
c=IN IP4 0.0.0.0
a=rtpmap:97 mpeg4-generic/48000/2
a=control:track2
a=fmtp: 97 streamtype=3;profile-level-id=14;mode=AAC-hbr;config=1190;sizeLength=13
```

### CODE REVIEW

**Comment by aler9** [comment]
Thanks for this contribution, getting documentation about MPEG stuff is always difficult and i knew i was missing something.

Please fix tests / linting and then i'll be able to review and merge.

**Comment by BenLocal** [comment]
linting seem to be modified according to this issues:
https://github.com/golangci/golangci-lint/issues/2649
```
  Running [/home/runner/golangci-lint-1.44.2-linux-amd64/golangci-lint run --out-format=github-actions] in [] ...
  panic: load embedded ruleguard rules: rules/rules.go:13: can't load fmt
  
  goroutine 1 [running]:
  github.com/go-critic/go-critic/checkers.init.22()
  	github.com/go-critic/go-critic@v0.6.2/checkers/embedded_rules.go:46 +0x4b4
```

**Comment by aler9** [comment]
You need to rebase the branch against main in order to fix conflicts and linting.

**Comment by BenLocal** [comment]
I repush #118, close this one

**Pull request closed without merging**
